In [1]:
import numpy as np

In [2]:
samples = ['我 毕业 于 北京邮电大学', '我 就职 于 字节跳动']

In [3]:
# 文本索引
token_index = {}
for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word] = len(token_index) + 1

print(token_index)

{'我': 1, '毕业': 2, '于': 3, '北京邮电大学': 4, '就职': 5, '字节跳动': 6}


In [4]:
# 第一种编码方式
res_1 = np.zeros(shape=(len(samples), len(token_index) + 1, max(token_index.values()) + 1))
print(res_1.shape)

for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split())):
        index = token_index.get(word)
        print(j, index, word)
        res_1[i, j, index] = 1
print(res_1)

(2, 7, 7)
0 1 我
1 2 毕业
2 3 于
3 4 北京邮电大学
0 1 我
1 5 就职
2 3 于
3 6 字节跳动
[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


In [5]:
# 第二种编码方式
res_2 = np.zeros(shape=(len(samples), max(token_index.values())+1))

for i, sample in enumerate(samples):
    # 第一种写法
    # for word in sample.split():
    # 第二种写法
    for _, word in list(enumerate(sample.split())):
        print(word)
        index = token_index.get(word)
        print(index)
        res_2[i, index] = 1
print(res_2)

我
1
毕业
2
于
3
北京邮电大学
4
我
1
就职
5
于
3
字节跳动
6
[[0. 1. 1. 1. 1. 0. 0.]
 [0. 1. 0. 1. 0. 1. 1.]]
